# Generated by Django 4.0.6 on 2022-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Введите название книги', max_length=100, verbose_name='Название книги'),
        ),
    ]
